import type {
  User,
  Employee,
  LeaveRequest,
  TravelOrder,
  AttendanceRecord,
  Document,
  Notification,
  DashboardStats,
  OrgStats,
} from '@/types';

// ── Auth / Current User ──────────────────────────────────────────────────────
export const mockUsers: User[] = [
  {
    id: 'u1',
    name: 'Maria Santos',
    email: 'maria.santos@lgu-sanjose.gov.ph',
    role: 'employee',
    department: 'Administrative Office',
    position: 'Administrative Aide IV',
    avatarInitials: 'MS',
    organizationId: 'org1',
    organizationName: 'Municipality of San Jose',
  },
  {
    id: 'u2',
    name: 'Ricardo Dela Cruz',
    email: 'rdc@lgu-sanjose.gov.ph',
    role: 'approver',
    department: 'Budget Office',
    position: 'Budget Officer II',
    avatarInitials: 'RD',
    organizationId: 'org1',
    organizationName: 'Municipality of San Jose',
  },
  {
    id: 'u3',
    name: 'Cynthia Reyes',
    email: 'creyes@lgu-sanjose.gov.ph',
    role: 'hr_admin',
    department: 'Human Resources',
    position: 'HRMO III',
    avatarInitials: 'CR',
    organizationId: 'org1',
    organizationName: 'Municipality of San Jose',
  },
  {
    id: 'u4',
    name: 'Mayor Eduardo Lim',
    email: 'mayor@lgu-sanjose.gov.ph',
    role: 'tenant_admin',
    department: "Mayor's Office",
    position: 'Local Chief Executive',
    avatarInitials: 'EL',
    organizationId: 'org1',
    organizationName: 'Municipality of San Jose',
  },
  {
    id: 'u5',
    name: 'Admin GovFlow',
    email: 'admin@govflow.ph',
    role: 'super_admin',
    department: 'GovFlow',
    position: 'Platform Administrator',
    avatarInitials: 'AG',
    organizationId: 'platform',
    organizationName: 'GovFlow',
  },
];

// ── Documents ────────────────────────────────────────────────────────────────
export const mockDocuments: Document[] = [
  {
    id: 'doc1',
    qrCode: 'GF-2026-TO-0041',
    type: 'travel_order',
    title: 'Travel Order — Quezon City Training',
    requester: 'Maria Santos',
    requesterDept: 'Administrative Office',
    status: 'in_review',
    currentHolder: 'Budget Officer',
    currentStep: 2,
    totalSteps: 4,
    submittedAt: '2026-07-01T08:30:00Z',
    updatedAt: '2026-07-03T14:22:00Z',
    destination: 'Quezon City',
    purpose: 'Seminar on Records Management',
    workflowSteps: [
      { id: 'ws1', stepNumber: 1, officeName: 'HR Admin', assigneeName: 'Cynthia Reyes', status: 'completed', completedAt: '2026-07-02T09:00:00Z', slaDays: 1, daysInStep: 1 },
      { id: 'ws2', stepNumber: 2, officeName: 'Budget Office', assigneeName: 'Ricardo Dela Cruz', status: 'current', slaDays: 2, daysInStep: 2 },
      { id: 'ws3', stepNumber: 3, officeName: 'Accounting Office', assigneeName: 'Ana Vergara', status: 'pending', slaDays: 1 },
      { id: 'ws4', stepNumber: 4, officeName: "Mayor's Office", assigneeName: 'Mayor Eduardo Lim', status: 'pending', slaDays: 1 },
    ],
  },
  {
    id: 'doc2',
    qrCode: 'GF-2026-LR-0087',
    type: 'leave_request',
    title: 'Vacation Leave — July 2026',
    requester: 'Jose Aquino',
    requesterDept: 'Engineering Office',
    status: 'pending',
    currentHolder: 'HR Admin',
    currentStep: 1,
    totalSteps: 2,
    submittedAt: '2026-07-05T10:00:00Z',
    updatedAt: '2026-07-05T10:00:00Z',
    dateRange: { from: '2026-07-14', to: '2026-07-18' },
    workflowSteps: [
      { id: 'ws5', stepNumber: 1, officeName: 'HR Admin', assigneeName: 'Cynthia Reyes', status: 'current', slaDays: 2, daysInStep: 0 },
      { id: 'ws6', stepNumber: 2, officeName: "Mayor's Office", assigneeName: 'Mayor Eduardo Lim', status: 'pending', slaDays: 1 },
    ],
  },
  {
    id: 'doc3',
    qrCode: 'GF-2026-PR-0023',
    type: 'purchase_request',
    title: 'Purchase Request — Office Supplies',
    requester: 'Luisa Fernandez',
    requesterDept: 'Health Office',
    status: 'approved',
    currentHolder: 'Completed',
    currentStep: 4,
    totalSteps: 4,
    submittedAt: '2026-06-28T08:00:00Z',
    updatedAt: '2026-07-04T16:30:00Z',
    workflowSteps: [
      { id: 'ws7', stepNumber: 1, officeName: 'Budget Office', assigneeName: 'Ricardo Dela Cruz', status: 'completed', completedAt: '2026-06-29T11:00:00Z', slaDays: 2, daysInStep: 1 },
      { id: 'ws8', stepNumber: 2, officeName: 'Accounting Office', assigneeName: 'Ana Vergara', status: 'completed', completedAt: '2026-07-01T14:00:00Z', slaDays: 2, daysInStep: 2 },
      { id: 'ws9', stepNumber: 3, officeName: 'Treasurer', assigneeName: 'Roberto Cruz', status: 'completed', completedAt: '2026-07-03T09:30:00Z', slaDays: 1, daysInStep: 2 },
      { id: 'ws10', stepNumber: 4, officeName: "Mayor's Office", assigneeName: 'Mayor Eduardo Lim', status: 'completed', completedAt: '2026-07-04T16:30:00Z', slaDays: 1, daysInStep: 1 },
    ],
  },
  {
    id: 'doc4',
    qrCode: 'GF-2026-JO-0015',
    type: 'job_order',
    title: 'Job Order — Road Repair Project',
    requester: 'Carlos Mendoza',
    requesterDept: 'Engineering Office',
    status: 'declined',
    currentHolder: 'HR Admin',
    currentStep: 1,
    totalSteps: 3,
    submittedAt: '2026-07-03T13:00:00Z',
    updatedAt: '2026-07-04T08:00:00Z',
    workflowSteps: [
      { id: 'ws11', stepNumber: 1, officeName: 'HR Admin', assigneeName: 'Cynthia Reyes', status: 'completed', comment: 'Missing supporting documents', slaDays: 1, daysInStep: 1 },
      { id: 'ws12', stepNumber: 2, officeName: 'Budget Office', assigneeName: 'Ricardo Dela Cruz', status: 'pending', slaDays: 2 },
      { id: 'ws13', stepNumber: 3, officeName: "Mayor's Office", assigneeName: 'Mayor Eduardo Lim', status: 'pending', slaDays: 1 },
    ],
  },
];

// ── Leave Requests ───────────────────────────────────────────────────────────
export const mockLeaveRequests: LeaveRequest[] = [
  {
    id: 'lr1',
    employeeId: 'e1',
    employeeName: 'Jose Aquino',
    department: 'Engineering Office',
    position: 'Engineer I',
    leaveType: 'vacation_leave',
    from: '2026-07-14',
    to: '2026-07-18',
    halfDay: false,
    days: 5,
    reason: 'Family vacation',
    status: 'pending',
    submittedAt: '2026-07-05T10:00:00Z',
  },
  {
    id: 'lr2',
    employeeId: 'e2',
    employeeName: 'Ana Vergara',
    department: 'Accounting Office',
    position: 'Accountant I',
    leaveType: 'sick_leave',
    from: '2026-07-07',
    to: '2026-07-08',
    halfDay: false,
    days: 2,
    reason: 'Medical checkup and rest',
    attachmentUrl: '/uploads/medical-cert.pdf',
    status: 'in_review',
    submittedAt: '2026-07-06T07:30:00Z',
  },
  {
    id: 'lr3',
    employeeId: 'e3',
    employeeName: 'Maria Santos',
    department: 'Administrative Office',
    position: 'Administrative Aide IV',
    leaveType: 'vacation_leave',
    from: '2026-06-20',
    to: '2026-06-21',
    halfDay: true,
    halfDayPeriod: 'pm',
    days: 1.5,
    reason: 'Personal matters',
    status: 'approved',
    submittedAt: '2026-06-15T09:00:00Z',
    approvedBy: 'Cynthia Reyes',
    approvedAt: '2026-06-17T14:00:00Z',
  },
  {
    id: 'lr4',
    employeeId: 'e4',
    employeeName: 'Carlos Mendoza',
    department: 'Engineering Office',
    position: 'Civil Engineer II',
    leaveType: 'force_leave',
    from: '2026-07-21',
    to: '2026-07-25',
    halfDay: false,
    days: 5,
    reason: 'Mandatory force leave',
    status: 'approved',
    submittedAt: '2026-07-01T08:00:00Z',
    approvedBy: 'Cynthia Reyes',
    approvedAt: '2026-07-02T10:00:00Z',
  },
];

// ── Travel Orders ────────────────────────────────────────────────────────────
export const mockTravelOrders: TravelOrder[] = [
  {
    id: 'to1',
    employeeId: 'e1',
    employeeName: 'Maria Santos',
    department: 'Administrative Office',
    destination: 'Quezon City',
    purpose: 'Seminar on Records Management',
    date: '2026-07-10',
    status: 'in_review',
    submittedAt: '2026-07-01T08:30:00Z',
  },
  {
    id: 'to2',
    employeeId: 'e2',
    employeeName: 'Ricardo Dela Cruz',
    department: 'Budget Office',
    destination: 'Manila',
    purpose: 'Budget Forum 2026',
    date: '2026-07-15',
    status: 'approved',
    submittedAt: '2026-07-02T09:00:00Z',
  },
];

// ── Attendance ───────────────────────────────────────────────────────────────
export const mockAttendance: AttendanceRecord[] = [
  { id: 'att1', employeeId: 'u1', date: '2026-07-07', timeIn: '2026-07-07T07:45:00Z', timeOut: '2026-07-07T17:00:00Z', status: 'present', hoursWorked: 8, overtimeMinutes: 0, undertimeMinutes: 0 },
  { id: 'att2', employeeId: 'u1', date: '2026-07-06', timeIn: '2026-07-06T08:10:00Z', timeOut: '2026-07-06T17:00:00Z', status: 'late', hoursWorked: 7.8, overtimeMinutes: 0, undertimeMinutes: 12 },
  { id: 'att3', employeeId: 'u1', date: '2026-07-05', timeIn: '2026-07-05T07:50:00Z', timeOut: '2026-07-05T17:00:00Z', status: 'present', hoursWorked: 8 },
  { id: 'att4', employeeId: 'u1', date: '2026-07-04', status: 'weekend' },
  { id: 'att5', employeeId: 'u1', date: '2026-07-03', status: 'on_leave' },
  { id: 'att6', employeeId: 'u1', date: '2026-07-02', timeIn: '2026-07-02T07:55:00Z', timeOut: '2026-07-02T17:00:00Z', status: 'present', hoursWorked: 8 },
  { id: 'att7', employeeId: 'u1', date: '2026-07-01', timeIn: '2026-07-01T07:48:00Z', timeOut: '2026-07-01T17:30:00Z', status: 'present', hoursWorked: 8.5, overtimeMinutes: 30 },
];

// ── Employees ────────────────────────────────────────────────────────────────
export const mockEmployees: Employee[] = [
  {
    id: 'e1',
    name: 'Maria Santos',
    email: 'maria.santos@lgu-sanjose.gov.ph',
    department: 'Administrative Office',
    position: 'Administrative Aide IV',
    status: 'active',
    dateHired: '2018-03-15',
    avatarInitials: 'MS',
    leaveCredits: {
      vacationLeave: { total: 15, used: 3, remaining: 12 },
      sickLeave: { total: 15, used: 0, remaining: 15 },
    },
    attendanceSummary: {
      present: 224,
      absent: 2,
      late: 8,
      onLeave: 6,
      officialBusiness: 4,
      workingDays: 244,
    },
  },
  {
    id: 'e2',
    name: 'Jose Aquino',
    email: 'jose.aquino@lgu-sanjose.gov.ph',
    department: 'Engineering Office',
    position: 'Engineer I',
    status: 'active',
    dateHired: '2020-06-01',
    avatarInitials: 'JA',
    leaveCredits: {
      vacationLeave: { total: 15, used: 8, remaining: 7 },
      sickLeave: { total: 15, used: 2, remaining: 13 },
    },
    attendanceSummary: {
      present: 210,
      absent: 5,
      late: 12,
      onLeave: 10,
      officialBusiness: 7,
      workingDays: 244,
    },
  },
  {
    id: 'e3',
    name: 'Ana Vergara',
    email: 'ana.vergara@lgu-sanjose.gov.ph',
    department: 'Accounting Office',
    position: 'Accountant I',
    status: 'active',
    dateHired: '2019-09-10',
    avatarInitials: 'AV',
    leaveCredits: {
      vacationLeave: { total: 15, used: 5, remaining: 10 },
      sickLeave: { total: 15, used: 4, remaining: 11 },
    },
    attendanceSummary: {
      present: 218,
      absent: 3,
      late: 5,
      onLeave: 9,
      officialBusiness: 9,
      workingDays: 244,
    },
  },
  {
    id: 'e4',
    name: 'Carlos Mendoza',
    email: 'carlos.mendoza@lgu-sanjose.gov.ph',
    department: 'Engineering Office',
    position: 'Civil Engineer II',
    status: 'active',
    dateHired: '2017-01-20',
    avatarInitials: 'CM',
    leaveCredits: {
      vacationLeave: { total: 15, used: 10, remaining: 5 },
      sickLeave: { total: 15, used: 1, remaining: 14 },
    },
    attendanceSummary: {
      present: 219,
      absent: 1,
      late: 15,
      onLeave: 5,
      officialBusiness: 4,
      workingDays: 244,
    },
  },
  {
    id: 'e5',
    name: 'Luisa Fernandez',
    email: 'luisa.fernandez@lgu-sanjose.gov.ph',
    department: 'Health Office',
    position: 'Public Health Nurse',
    status: 'active',
    dateHired: '2021-04-05',
    avatarInitials: 'LF',
    leaveCredits: {
      vacationLeave: { total: 15, used: 1, remaining: 14 },
      sickLeave: { total: 15, used: 0, remaining: 15 },
    },
    attendanceSummary: {
      present: 230,
      absent: 0,
      late: 3,
      onLeave: 1,
      officialBusiness: 10,
      workingDays: 244,
    },
  },
];

// ── Notifications ────────────────────────────────────────────────────────────
export const mockNotifications: Notification[] = [
  {
    id: 'n1',
    title: 'Travel Order Approved',
    message: 'Your Travel Order to Quezon City has been forwarded to Accounting Office.',
    type: 'approval',
    read: false,
    createdAt: '2026-07-03T14:22:00Z',
  },
  {
    id: 'n2',
    title: 'New Leave Request',
    message: 'Jose Aquino submitted a Vacation Leave request for July 14-18.',
    type: 'info',
    read: false,
    createdAt: '2026-07-05T10:00:00Z',
  },
  {
    id: 'n3',
    title: 'SLA Warning',
    message: 'Purchase Request GF-2026-PR-0023 has exceeded 2-day SLA in Budget Office.',
    type: 'warning',
    read: true,
    createdAt: '2026-07-01T09:00:00Z',
  },
  {
    id: 'n4',
    title: 'Leave Approved',
    message: 'Your Vacation Leave for June 20-21 has been approved.',
    type: 'approval',
    read: true,
    createdAt: '2026-06-17T14:00:00Z',
  },
];

// ── Dashboard Stats ──────────────────────────────────────────────────────────
export const mockDashboardStats: DashboardStats = {
  totalEmployees: 127,
  presentToday: 98,
  absentToday: 12,
  lateToday: 8,
  onLeave: 5,
  officialBusiness: 4,
  pendingRequests: 14,
  approvedToday: 7,
  declinedToday: 2,
};

export const mockOrgStats: OrgStats = {
  documentsInProcess: 127,
  delayed: 18,
  pendingSignature: 6,
  averageProcessingDays: 2.3,
  mostDelayedOffice: 'Accounting Office',
};

// ── Chart Data ───────────────────────────────────────────────────────────────
export const mockDocumentTrends = [
  { month: 'Jan', travelOrders: 24, leaveRequests: 38, jobOrders: 12, purchaseRequests: 8 },
  { month: 'Feb', travelOrders: 18, leaveRequests: 42, jobOrders: 15, purchaseRequests: 11 },
  { month: 'Mar', travelOrders: 31, leaveRequests: 29, jobOrders: 18, purchaseRequests: 9 },
  { month: 'Apr', travelOrders: 22, leaveRequests: 35, jobOrders: 14, purchaseRequests: 13 },
  { month: 'May', travelOrders: 27, leaveRequests: 31, jobOrders: 11, purchaseRequests: 7 },
  { month: 'Jun', travelOrders: 19, leaveRequests: 44, jobOrders: 16, purchaseRequests: 10 },
  { month: 'Jul', travelOrders: 8, leaveRequests: 22, jobOrders: 7, purchaseRequests: 5 },
];

export const mockAttendanceTrends = [
  { week: 'Wk 1', present: 95, late: 12, absent: 8, onLeave: 12 },
  { week: 'Wk 2', present: 98, late: 8, absent: 6, onLeave: 15 },
  { week: 'Wk 3', present: 91, late: 15, absent: 11, onLeave: 10 },
  { week: 'Wk 4', present: 97, late: 9, absent: 5, onLeave: 16 },
];
